# SPDX-License-Identifier: GPL-2.0+

ccflags-y += -I$(srctree)/lib/lwip-port/lwip/src/include \
	-I$(srctree)/lib/lwip-port/port/include

obj-y += core.o
obj-y += dhcp.o
obj-y += ping.o
obj-y += tftp.o
obj-y += http.o
